stages:
  - deploy

test_variable:
  image: alpine:latest
  variables:
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  no_proxy: .siemens.com
  stage: deploy
  script:
    - echo "$CI_JOB_STAGE"
    - echo "$CI_PIPELINE_IID"
  artifacts:
    untracked: false
    expire_in: "30 days"
    paths:
      - ./public
