stages:
  - deploy

test_variable:
  image: alpine:late
  stage: deploy
  script:
    - echo "$CI_JOB_STAGE"
    - echo "$CI_PIPELINE_IID"
  artifacts:
    untracked: false
    expire_in: "30 days"
    paths:
      - ./public
